blueprint:
  name: Bilvärmare – temperaturstyrd (2 notifier)
  description: >
    Startar motorvärmare baserat på aktuell utomhustemperatur
    och vald avgångstid (alltid dagens datum).
    Skickar notis när värmaren slås på.
  domain: automation

  input:
    departure_time:
      name: Avgångstid
      selector:
        entity:
          domain: input_datetime

    outdoor_temp:
      name: Utomhustemperatur
      selector:
        entity:
          domain: sensor
          device_class: temperature

    heater_switch:
      name: Motorvärmare
      selector:
        entity:
          domain: switch

    enabled_switch:
      name: Automation aktiv
      selector:
        entity:
          domain: input_boolean

    weekdays_only:
      name: Endast vardagar
      selector:
        entity:
          domain: input_boolean

    notify_target_1:
      name: Notis mottagare 1
      description: Välj notify.mobile_app_* (valfri)
      selector:
        entity:
          domain: notify

    notify_target_2:
      name: Notis mottagare 2
      description: Välj notify.mobile_app_* (valfri)
      selector:
        entity:
          domain: notify

mode: single

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  temp_sensor: !input outdoor_temp
  heater: !input heater_switch
  enabled: !input enabled_switch
  weekdays_only: !input weekdays_only
  depart_entity: !input departure_time

  now_ts: "{{ now().timestamp() }}"

  # Avgångstid – alltid IDAG
  depart_ts: >
    {% set t = states(depart_entity) %}
    {% if t in ('unknown', 'unavailable', '') %}
      0
    {% else %}
      {{ today_at(t).timestamp() }}
    {% endif %}

  # Aktuell temperatur
  temp: "{{ states(temp_sensor) | float(99) }}"

  # Uppvärmningstid i sekunder
  heat_seconds: >
    {% if temp < -20 %}
      10800
    {% elif temp < -10 %}
      7200
    {% elif temp < 0 %}
      3600
    {% elif temp < 5 %}
      1800
    {% else %}
      0
    {% endif %}

  start_ts: "{{ depart_ts - heat_seconds }}"

condition:
  - condition: state
    entity_id: !input enabled_switch
    state: "on"

  - condition: template
    value_template: "{{ heat_seconds > 0 }}"

  - condition: template
    value_template: "{{ depart_ts > now_ts }}"

  - condition: template
    value_template: >
      {% if is_state(weekdays_only, 'on') %}
        {{ now().weekday() < 5 }}
      {% else %}
        true
      {% endif %}

action:
  - choose:
      # 🔥 STARTA VÄRMAREN
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts >= start_ts and now_ts < depart_ts }}
          - condition: state
            entity_id: !input heater_switch
            state: "off"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input heater_switch

          # 🔔 NOTIS 1
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_target_1 is defined }}"
                sequence:
                  - service: !input notify_target_1
                    data:
                      title: "🚗 Motorvärmare"
                      message: "Motorvärmaren har startat."

          # 🔔 NOTIS 2
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notify_target_2 is defined }}"
                sequence:
                  - service: !input notify_target_2
                    data:
                      title: "🚗 Motorvärmare"
                      message: "Motorvärmaren har startat."

      # ⛔ STÄNG AV EFTER AVGÅNG
      - conditions:
          - condition: template
            value_template: "{{ now_ts >= depart_ts }}"
          - condition: state
            entity_id: !input heater_switch
            state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
