blueprint:
  name: Bilvärmare – säker & korrigerad
  description: >
    Startar motorvärmare baserat på aktuell utomhustemperatur
    och avgångstid (alltid dagens datum).
    Inga notifieringar. Ingen prognos. Säker avstängning.
  domain: automation

  input:
    departure_time:
      name: Avgångstid
      selector:
        entity:
          domain: input_datetime

    outdoor_temp:
      name: Utomhustemperatur
      selector:
        entity:
          domain: sensor
          device_class: temperature

    heater_switch:
      name: Motorvärmare
      selector:
        entity:
          domain: switch

    enabled_switch:
      name: Automation aktiv
      selector:
        entity:
          domain: input_boolean

    weekdays_only:
      name: Endast vardagar
      selector:
        entity:
          domain: input_boolean

mode: single

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  now_ts: "{{ now().timestamp() }}"

  depart_time_entity: !input departure_time
  temp_entity: !input outdoor_temp
  weekdays_entity: !input weekdays_only

  depart_ts: >
    {% set t = states(depart_time_entity) %}
    {% if t in ('unknown', 'unavailable', '') %}
      0
    {% else %}
      {{ today_at(t).timestamp() }}
    {% endif %}

  temp: "{{ states(temp_entity) | float(99) }}"

  heat_seconds: >
    {% if temp < -20 %}
      10800
    {% elif temp < -10 %}
      7200
    {% elif temp < 0 %}
      3600
    {% elif temp < 5 %}
      1800
    {% else %}
      0
    {% endif %}

  start_ts: "{{ depart_ts - heat_seconds }}"

  max_off_ts: "{{ start_ts + 10800 }}"   # MAX 3 timmar från start

condition:
  # Automation aktiv
  - condition: state
    entity_id: !input enabled_switch
    state: "on"

  # Avgång måste finnas
  - condition: template
    value_template: "{{ depart_ts > 0 }}"

  # Endast vardagar (valbart)
  - condition: template
    value_template: >
      {% if is_state(weekdays_entity, 'on') %}
        {{ now().weekday() < 5 }}
      {% else %}
        true
      {% endif %}

action:
  - choose:

      # 🔥 STARTA VÄRMAREN
      - conditions:
          - condition: template
            value_template: >
              {{ heat_seconds > 0
                 and now_ts >= start_ts
                 and now_ts < depart_ts }}
          - condition: state
            entity_id: !input heater_switch
            state: "off"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input heater_switch

      # ⛔ STÄNG AV VID AVGÅNG ELLER MAX 3H
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts >= depart_ts
                 or now_ts >= max_off_ts }}
          - condition: state
            entity_id: !input heater_switch
            state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
