blueprint:
  name: Bilvärmare – ren & optimerad
  description: >
    Startar motorvärmare baserat på aktuell utomhustemperatur
    och vald avgångstid (alltid dagens datum).
    Tydliga conditions. Ingen prognos. Inga notifieringar.
  domain: automation

  input:
    departure_time:
      name: Avgångstid
      selector:
        entity:
          domain: input_datetime

    outdoor_temp:
      name: Utomhustemperatur
      selector:
        entity:
          domain: sensor
          device_class: temperature

    heater_switch:
      name: Motorvärmare
      selector:
        entity:
          domain: switch

    enabled_switch:
      name: Automation aktiv
      selector:
        entity:
          domain: input_boolean

    weekdays_only:
      name: Endast vardagar
      selector:
        entity:
          domain: input_boolean

mode: single

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  now_ts: "{{ now().timestamp() }}"

  depart_time_entity: !input departure_time
  temp_entity: !input outdoor_temp

  depart_ts: >
    {% set t = states(depart_time_entity) %}
    {% if t in ('unknown', 'unavailable', '') %}
      0
    {% else %}
      {{ today_at(t).timestamp() }}
    {% endif %}
  temp: "{{ states(temp_entity) | float(99) }}"

  heat_seconds: >
    {% if temp < -20 %}
      10800
    {% elif temp < -10 %}
      7200
    {% elif temp < 0 %}
      3600
    {% elif temp < 5 %}
      1800
    {% else %}
      0
    {% endif %}
  start_ts: "{{ depart_ts - heat_seconds }}"

condition:
  # Automation aktiv
  - condition: state
    entity_id: !input enabled_switch
    state: "on"

  # Värme behövs
  - condition: template
    value_template: "{{ heat_seconds > 0 }}"

  # Avgång i framtiden
  - condition: template
    value_template: "{{ depart_ts > now_ts }}"

  # Endast vardagar (valbart)
  - condition: template
    value_template: >
      {% if is_state('!input weekdays_only', 'on') %}
        {{ now().weekday() < 5 }}
      {% else %}
        true
      {% endif %}
action:
  - choose:
      # 🔥 SLÅ PÅ
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts >= start_ts and now_ts < depart_ts }}
          - condition: state
            entity_id: !input heater_switch
            state: "off"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input heater_switch

      # ⛔ SLÅ AV
      - conditions:
          - condition: template
            value_template: "{{ now_ts >= depart_ts }}"
          - condition: state
            entity_id: !input heater_switch
            state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
